<?php
define("DB_HOST","localhost");
define("DB_NAME","Employee_form");
define("DB_USERNAME","root");
define("DB_PASSWORD","");
/*
define("DB_HOST","127.0.0.1");
define("DB_NAME","oasiswebsoft");
define("DB_USERNAME","root");
define("DB_PASSWORD","Gyimah@15");*/
?>
